Repository ProgramadoresArgentina/proyecto-ada, pull requests merged in 2023-08, with the labels that each got.

#66 table Articles created
  pages/api/articles/articles.ts
  prisma/schema.prisma
Labels: Ready to merge

#63 Plat 64 crear ruta dinamica y columna en tabla user settings
  components/Portfolio/404.tsx
  components/Portfolio/Portfolio.tsx
  data/dummy-data.js
  next.config.js
  pages/pro/[userId]/index.tsx
  prisma/schema.prisma
  public/portfolio/blogger.svg
  public/portfolio/certification.svg
  public/portfolio/complete-profile.svg
  public/portfolio/cv.svg
  public/portfolio/education.svg
  public/portfolio/experience.svg
  public/portfolio/github.svg
  public/portfolio/information.svg
  public/portfolio/link.svg
  public/portfolio/linkedin.svg
  public/portfolio/member.svg
  public/portfolio/proyects.svg
  public/portfolio/socials.svg
Labels: DONT MERGE

#71 PLAT-68: [url].ts - get user info to show in userProfile /pro
  pages/api/users/userProfile/[url].ts
Labels: DONT MERGE

#76 remove loading from dependencies
  pages/validate/index.tsx
Labels: Ready to merge

#89 Remove Validate page, redirects to /validate changed to /
  components/navbar.tsx
  pages/api/auth/[...auth0].ts
Labels: DONT MERGE, question
